spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.1"
              memory: 64Mi
            limits:
              cpu: "0.4"
              memory: 200Mi
          env:
          - name: INFINISPAN_SERVICE
            value: datagrid-app-hotrod